name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/henshi-web
      BUILD_CONFIGURATION: Release
      INFRA_REPO: henshiapp/henshi-infra
      DEPLOYMENT_FILE: apps/staging/web/deployment.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.semantic-release.outputs.next_release_version || github.sha }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_CONFIGURATION=${{ env.BUILD_CONFIGURATION }}
            PUBLISH_TRIMMED=false
            PUBLISH_RTR=false
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cache,mode=max

      - name: Checkout infra repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.INFRA_REPO }}
          token: ${{ secrets.REPO_PAT }}

      - name: Update deployment.yaml image tag
        run: |
          sed -i "s|image: ${IMAGE_NAME}:.*|image: ${IMAGE_NAME}:${{ steps.semantic-release.outputs.next_release_version || github.sha }}|" ${DEPLOYMENT_FILE}

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${DEPLOYMENT_FILE}
          git commit -m "chore: update web image to ${{ steps.semantic-release.outputs.next_release_version || github.sha }}" || echo "No changes to commit"
          git push origin main